//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAbout> TBLAbout { get; set; }
        public virtual DbSet<TBLCommunication> TBLCommunication { get; set; }
        public virtual DbSet<TBLEducation> TBLEducation { get; set; }
        public virtual DbSet<TBLExperiences> TBLExperiences { get; set; }
        public virtual DbSet<TBLHobbies> TBLHobbies { get; set; }
        public virtual DbSet<TBLSertificates> TBLSertificates { get; set; }
        public virtual DbSet<TBLSkill> TBLSkill { get; set; }
        public virtual DbSet<TBLUser> TBLUser { get; set; }
    }
}
